#############################################################################
# File name:  Makefile
# Author:     Frisk oster
# Date:       11.23.19
# Class:      CS 300
# Assignment: HashTable
# Purpose: 	  This is the Makefile for the Invoice program  
#############################################################################

CC=gcc
CFLAGS=-Wall -g

.PHONY: all clean
